"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import logging
import os
import re
import sys
from pathlib import Path
from urllib.parse import parse_qs, unquote_plus, urlparse

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Variables de entorno (.env en la raíz del proyecto). Ver .env.example
env = environ.Env(
    DEBUG=(bool, True),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_USE_SSL=(bool, False),
)
# En App Platform / PaaS no debe existir .env en el repo; las credenciales van en el panel.
# Si hay .env local, no debe pisar variables ya definidas en el entorno del despliegue.
environ.Env.read_env(BASE_DIR / ".env", overwrite=False)


def _fill_postgres_from_dotenv_if_system_empty() -> None:
    """En Windows a veces hay POSTGRES_PASSWORD= (vacío) a nivel de usuario; read_env(overwrite=False) no lo pisa.

    Si el proceso tiene la clave vacía o ausente pero el .env define un valor, lo aplicamos desde el archivo.
    """
    path = BASE_DIR / ".env"
    if not path.is_file():
        return
    keys = frozenset(
        {
            "POSTGRES_DB",
            "POSTGRES_USER",
            "POSTGRES_PASSWORD",
            "POSTGRES_HOST",
            "POSTGRES_PORT",
            "POSTGRES_SSLMODE",
        }
    )
    try:
        raw = path.read_text(encoding="utf-8-sig")
    except OSError:
        return
    for line in raw.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if "=" not in s:
            continue
        k, _, rest = s.partition("=")
        k = k.strip()
        if k not in keys:
            continue
        v = rest.strip()
        if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
            v = v[1:-1]
        if (os.environ.get(k) or "").strip():
            continue
        os.environ[k] = v


_fill_postgres_from_dotenv_if_system_empty()


def _env_flag_true(val: str | None) -> bool:
    return (val or "").strip().lower() in ("1", "true", "yes", "on")


# Windows / IDEs a veces exportan DATABASE_URL o PGHOST hacia la nube antes que el .env.
# Con overwrite=False esas claves ganan y el .env nunca las corrige. Si el desarrollador pide
# modo local (DJANGO_IGNORE_DATABASE_URL=1), quitamos esas claves y releemos .env con prioridad.
_dotenv_path = BASE_DIR / ".env"
_cloud_db_url_keys = (
    "DATABASE_URL",
    "POSTGRES_URL",
    "POSTGRESQL_URL",
    "POSTGRES_DATABASE_URL",
)
_cloud_pg_keys = (
    "PGHOST",
    "PGUSER",
    "PGPASSWORD",
    "PGDATABASE",
    "PGPORT",
    "DB_HOST",
    "DB_USER",
    "DB_PASSWORD",
    "DB_NAME",
    "DB_PORT",
)
if _dotenv_path.is_file() and _env_flag_true(os.environ.get("DJANGO_IGNORE_DATABASE_URL")):
    for _k in _cloud_db_url_keys + _cloud_pg_keys:
        os.environ.pop(_k, None)
    environ.Env.read_env(_dotenv_path, overwrite=True)
    # Aunque el .env defina DATABASE_URL, en este modo solo deben valer POSTGRES_*.
    for _k in _cloud_db_url_keys:
        os.environ.pop(_k, None)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    "SECRET_KEY",
    default="django-insecure-(s#lp8&jfs)zgn9jfn05m_9aj5dtw2yns7%t3kgv6jv_cj1)&8",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

# PaaS (PORT presente): no arrancar con DEBUG o SECRET_KEY de ejemplo.
# Escape: DJANGO_ALLOW_INSECURE_PROD=1 (solo diagnóstico).
if os.environ.get("PORT") and not env.bool("DJANGO_ALLOW_INSECURE_PROD", default=False):
    from django.core.exceptions import ImproperlyConfigured

    if DEBUG:
        raise ImproperlyConfigured(
            "DEBUG debe ser False en producción (variable PORT presente). "
            "Defina DEBUG=False en el panel del Web Service."
        )
    if str(SECRET_KEY).startswith("django-insecure") or len(str(SECRET_KEY)) < 40:
        raise ImproperlyConfigured(
            "Defina SECRET_KEY fuerte y aleatoria en producción (mín. 40 caracteres)."
        )

# Auditoría por señales (crear/editar/borrar en modelos de negocio). Desactívela con AUDIT_SIGNALS_ENABLED=0 si no la necesita.
AUDIT_SIGNALS_ENABLED = env.bool("AUDIT_SIGNALS_ENABLED", default=True)

# En desarrollo permite acceder por localhost; en producción definir dominios reales.
ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["127.0.0.1", "localhost", "[::1]"],
)

# DigitalOcean App Platform: el Host es *.ondigitalocean.app. Sin esto aparece DisallowedHost
# si no configuró DJANGO_ALLOWED_HOSTS en el panel (o el deploy no trae el último código).
# Desactivar solo si no usa App Platform: DJANGO_DISABLE_ONDIGITALOCEAN_HOST=1
if not env.bool("DJANGO_DISABLE_ONDIGITALOCEAN_HOST", default=False):
    _do_suffix = ".ondigitalocean.app"
    if _do_suffix not in ALLOWED_HOSTS:
        ALLOWED_HOSTS = list(ALLOWED_HOSTS) + [_do_suffix]

# HTTPS detrás de proxy (nginx, DigitalOcean App Platform, load balancer).
# En DEBUG local no confiar en X-Forwarded-Proto: rompe cookies CSRF en http://127.0.0.1.
USE_X_FORWARDED_HOST = env.bool(
    "DJANGO_USE_X_FORWARDED_HOST",
    default=not DEBUG,
)
if env.bool("DJANGO_SECURE_PROXY_SSL_HEADER", default=not DEBUG):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
else:
    SECURE_PROXY_SSL_HEADER = None

# Orígenes confiables para CSRF (ej. https://tu-app.ondigitalocean.app)
_csrf_origins = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])
_pbu_csrf = env.str("PUBLIC_BASE_URL", default="").strip().rstrip("/")
if _pbu_csrf.startswith("http") and _pbu_csrf not in _csrf_origins:
    CSRF_TRUSTED_ORIGINS = list(_csrf_origins) + [_pbu_csrf]
else:
    CSRF_TRUSTED_ORIGINS = list(_csrf_origins)

# Desarrollo local: asegurar orígenes http aunque falten en .env
if DEBUG:
    for _origin in (
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "http://127.0.0.1:8001",
        "http://localhost:8001",
    ):
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SAMESITE = "Lax"

if not DEBUG:
    SESSION_COOKIE_SECURE = env.bool("DJANGO_SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", default=True)
    SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=False)

# WhiteNoise: Gunicorn (App Platform) no sirve estáticos como runserver. Con DEBUG=True
# en el panel muchos equipos olvidan DJANGO_USE_WHITENOISE=1; si existe PORT (DO/Heroku), activar.
DJANGO_USE_WHITENOISE = env.bool(
    "DJANGO_USE_WHITENOISE",
    default=(not DEBUG or bool(os.environ.get("PORT"))),
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'audit.apps.AuditConfig',
    'inmobiliaria.apps.InmobiliariaConfig',
    'crm.apps.CrmConfig',
    'docs.apps.DocsConfig',
    'usuarios.apps.UsuariosConfig',
    'storages',
]

def _build_middleware():
    mw = []
    if env.bool("PBR_URLCONF_PROBE", default=DEBUG):
        mw.append("core.middleware.UrlConfProbeMiddleware")
    mw.append("django.middleware.security.SecurityMiddleware")
    if DJANGO_USE_WHITENOISE:
        mw.append("whitenoise.middleware.WhiteNoiseMiddleware")
    mw.extend(
        [
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "usuarios.middleware.AppUsuarioActivoMiddleware",
            "inmobiliaria.middleware.VendedorFlujoMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "audit.middleware.AuditContextMiddleware",
        ]
    )
    return mw


MIDDLEWARE = _build_middleware()

ROOT_URLCONF = "backend.urls"

# Almacenamiento de archivos (media + estáticos recopilados)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage"
            if DJANGO_USE_WHITENOISE
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.perfil_app',
                'core.context_processors.sidebar_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database — PostgreSQL
# Variables: POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST, POSTGRES_PORT
# Crear la base antes: CREATE DATABASE nombre OWNER usuario ENCODING 'UTF8';
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_pg_options = {"connect_timeout": 10}
_postgres_sslmode = env.str("POSTGRES_SSLMODE", default="").strip()
if _postgres_sslmode:
    _pg_options["sslmode"] = _postgres_sslmode


def _pbr_local_db_warnings_enabled() -> bool:
    """El padre de `runserver` importa settings antes que el hijo; sin esto los avisos PBR salen duplicados."""
    if "runserver" in sys.argv and os.environ.get("RUN_MAIN") != "true":
        return False
    return True


def _first_database_url_raw() -> str:
    """Cadena de conexión; varias plataformas usan nombres distintos."""
    for key in (
        "DATABASE_URL",
        "POSTGRES_URL",
        "POSTGRESQL_URL",
        "POSTGRES_DATABASE_URL",
    ):
        v = (os.environ.get(key) or "").strip()
        if v and not v.startswith("${"):
            # Valor enlazado no resuelto en el panel de DO (literal ${db...})
            return v
    return ""


def _database_from_url() -> dict | None:
    """DigitalOcean App Platform suele inyectar DATABASE_URL al vincular PostgreSQL."""
    raw = _first_database_url_raw()
    if not raw:
        return None
    u = urlparse(raw)
    if u.scheme not in ("postgres", "postgresql"):
        return None
    path = (u.path or "").lstrip("/")
    dbname = path.split("/")[0] or "postgres"
    opts: dict = {"connect_timeout": 10}
    q = parse_qs(u.query)
    if q.get("sslmode"):
        opts["sslmode"] = q["sslmode"][0]
    elif u.hostname and "digitalocean" in u.hostname:
        opts["sslmode"] = "require"
    if _postgres_sslmode and "sslmode" not in opts:
        opts["sslmode"] = _postgres_sslmode
    user = (unquote_plus(u.username or "") or "").strip()
    password = (unquote_plus(u.password or "") or "").strip()
    # Si la contraseña en la URL está mal copiada o con caracteres que rompen el parseo,
    # defina POSTGRES_PASSWORD (o PGPASSWORD) en el panel: sustituye la de DATABASE_URL.
    _pw_override = (os.environ.get("POSTGRES_PASSWORD") or os.environ.get("PGPASSWORD") or "").strip()
    if _pw_override:
        password = _pw_override
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote_plus(dbname),
        "USER": user,
        "PASSWORD": password,
        "HOST": u.hostname or "",
        "PORT": str(u.port or 5432),
        "OPTIONS": opts,
    }


def _database_from_pg_env() -> dict | None:
    """Variables estilo libpq (PGHOST, PGDATABASE, …) que algunos entornos inyectan."""
    host = (
        (os.environ.get("PGHOST") or os.environ.get("POSTGRES_HOSTNAME") or "").strip()
    )
    if not host:
        return None
    opts: dict = {"connect_timeout": 10}
    if _postgres_sslmode:
        opts["sslmode"] = _postgres_sslmode
    elif "digitalocean" in host:
        opts["sslmode"] = "require"
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": (os.environ.get("PGDATABASE") or env.str("POSTGRES_DB", default="paredes_bienes")).strip(),
        "USER": (os.environ.get("PGUSER") or "").strip(),
        "PASSWORD": (os.environ.get("PGPASSWORD") or "").strip(),
        "HOST": host,
        "PORT": str((os.environ.get("PGPORT") or "5432")).strip(),
        "OPTIONS": opts,
    }


def _database_from_db_prefix() -> dict | None:
    """Convención DB_HOST / DB_NAME / … usada en algunos tutoriales y paneles."""
    host = (os.environ.get("DB_HOST") or "").strip()
    if not host:
        return None
    opts: dict = {"connect_timeout": 10}
    if _postgres_sslmode:
        opts["sslmode"] = _postgres_sslmode
    elif "digitalocean" in host:
        opts["sslmode"] = "require"
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": (os.environ.get("DB_NAME") or env.str("POSTGRES_DB", default="paredes_bienes")).strip(),
        "USER": (os.environ.get("DB_USER") or "").strip(),
        "PASSWORD": (os.environ.get("DB_PASSWORD") or "").strip(),
        "HOST": host,
        "PORT": str((os.environ.get("DB_PORT") or "5432")).strip(),
        "OPTIONS": opts,
    }


# Modo local: ignore DATABASE_URL, PGHOST, DB_HOST, etc. (a menudo heredados de la nube / variables
# de sistema en Windows) y use solo POSTGRES_* del .env — ver DJANGO_IGNORE_DATABASE_URL en .env.example.
_use_only_postgres_env_file = env.bool("DJANGO_IGNORE_DATABASE_URL", default=False)
if _use_only_postgres_env_file:
    _db_url = None
    _db_pg = None
    _db_alt = None
else:
    _db_url = _database_from_url()
    _db_pg = _database_from_pg_env()
    _db_alt = _database_from_db_prefix()
if _db_url:
    DATABASES = {"default": _db_url}
elif _db_pg:
    DATABASES = {"default": _db_pg}
elif _db_alt:
    DATABASES = {"default": _db_alt}
else:
    _pg_host = env.str("POSTGRES_HOST", default="localhost").strip() or "localhost"
    if _use_only_postgres_env_file and "ondigitalocean.com" in _pg_host.lower():
        if _pbr_local_db_warnings_enabled():
            logging.getLogger(__name__).warning(
                "PBR: POSTGRES_HOST apunta a DigitalOcean (%s); en modo local se usa localhost. "
                "Corrija su .env si necesita otro host.",
                _pg_host,
            )
        _pg_host = "localhost"
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env.str("POSTGRES_DB", default="paredes_bienes"),
            "USER": env.str("POSTGRES_USER", default="postgres"),
            "PASSWORD": env.str("POSTGRES_PASSWORD", default=""),
            "HOST": _pg_host,
            "PORT": env.str("POSTGRES_PORT", default="5432"),
            "OPTIONS": dict(_pg_options),
        }
    }


def _normalize_db_for_local_dev(db: dict) -> None:
    """Evita fallos típicos en Windows con un .env copiado de DigitalOcean.

    - Host *.ondigitalocean.com no resuelve sin red/VPN → localhost.
    - Tras localhost suelen quedar POSTGRES_PORT=25060 y sslmode=require (DO), incompatibles con Postgres local.

    No aplica en PaaS (PORT en el entorno). Para usar el host remoto desde su PC: DJANGO_ALLOW_REMOTE_DO_DB=1.
    """
    if os.environ.get("PORT") or env.bool("DJANGO_ALLOW_REMOTE_DO_DB", default=False):
        return
    log = logging.getLogger(__name__)
    _say = _pbr_local_db_warnings_enabled()
    host = (db.get("HOST") or "").strip()
    host_l = host.lower()
    try:
        p = int(str(db.get("PORT") or "5432").strip() or "5432")
    except ValueError:
        p = 5432
    opts = db.get("OPTIONS") if isinstance(db.get("OPTIONS"), dict) else {}
    ssl_require = (opts.get("sslmode") or "").lower() == "require"

    coerced_host = False
    coerced_port = False
    if host_l and "ondigitalocean.com" in host_l:
        if _say:
            log.warning(
                "PBR: desarrollo local: host «%s» (DigitalOcean) → localhost. "
                "Defina POSTGRES_* para su Postgres local o DJANGO_ALLOW_REMOTE_DO_DB=1 para forzar remoto.",
                host,
            )
        db["HOST"] = "localhost"
        coerced_host = True
        host_l = "localhost"

    is_loopback = host_l in ("localhost", "127.0.0.1", "::1") or host_l.startswith("[::1]")
    if is_loopback and p > 10000:
        if _say:
            log.warning(
                "PBR: puerto %s (típico de BD en la nube) → 5432 para Postgres local.",
                db.get("PORT"),
            )
        db["PORT"] = "5432"
        coerced_port = True

    if is_loopback and ssl_require and (coerced_host or coerced_port):
        db["OPTIONS"] = {k: v for k, v in opts.items() if k != "sslmode"}
        if coerced_port and not coerced_host and _say:
            log.warning(
                "PBR: sslmode=require omitido para Postgres local (defina POSTGRES_SSLMODE si usa TLS en local)."
            )

    if (coerced_host or coerced_port) and is_loopback:
        u = (db.get("USER") or "").strip().lower()
        if u == "doadmin" and _say:
            log.warning(
                "PBR: POSTGRES_USER es «doadmin» (DigitalOcean) pero la conexión va a localhost; fallará la "
                "autenticación hasta que en .env ponga POSTGRES_USER, POSTGRES_PASSWORD y POSTGRES_DB de su Postgres "
                "local, o DJANGO_ALLOW_REMOTE_DO_DB=1 si usa la BD en la nube."
            )


_normalize_db_for_local_dev(DATABASES["default"])

# Gunicorn en App Platform define PORT; no forzar fallo al arrancar si aún no hay DATABASE_URL
# (un raise aquí tumba Gunicorn y el health check). Solo avisar en logs.
_running_on_paas = bool(os.environ.get("PORT"))
_local_hosts = frozenset({"localhost", "127.0.0.1", "::1", "[::1]"})
if _running_on_paas:
    _dh = (DATABASES["default"].get("HOST") or "").strip()
    if _dh in _local_hosts and not env.bool("DJANGO_ALLOW_LOCALHOST_DB", default=False):
        logging.getLogger(__name__).warning(
            "PBR: PORT (PaaS) activo pero la BD sigue en localhost. "
            "Defina DATABASE_URL o POSTGRES_* en el Web Service; sin eso el login fallará. "
            "Vea deploy/DIGITALOCEAN.md."
        )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-sv'

TIME_ZONE = 'America/El_Salvador'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / 'static']

# collectstatic → esta carpeta (producción + WhiteNoise)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media (PDFs emitidos, planos, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Con DEBUG=False, /media/ no se sirve salvo que active esto (enlace HTTPS en WhatsApp vía PUBLIC_BASE_URL).
# Los PDF quedan accesibles sin login por URL; use solo si acepta ese riesgo o proteja con otro mecanismo.
DJANGO_SERVE_MEDIA_PUBLIC = env.bool("DJANGO_SERVE_MEDIA_PUBLIC", default=False)

# --- Almacenamiento S3-compatible (DigitalOcean Spaces, AWS S3, MinIO) ---
# Con DJANGO_USE_S3_MEDIA=1 los FileField se guardan en el bucket (sobreviven a redeploy en App Platform).
DJANGO_USE_S3_MEDIA = env.bool("DJANGO_USE_S3_MEDIA", default=False)
AWS_ACCESS_KEY_ID = env.str("AWS_ACCESS_KEY_ID", default="").strip()
AWS_SECRET_ACCESS_KEY = env.str("AWS_SECRET_ACCESS_KEY", default="").strip()
AWS_STORAGE_BUCKET_NAME = env.str("AWS_STORAGE_BUCKET_NAME", default="").strip()
AWS_S3_REGION_NAME = env.str("AWS_S3_REGION_NAME", default="").strip()
AWS_S3_ENDPOINT_URL = env.str("AWS_S3_ENDPOINT_URL", default="").strip()
AWS_S3_CUSTOM_DOMAIN = env.str("AWS_S3_CUSTOM_DOMAIN", default="").strip()
AWS_DEFAULT_ACL = env.str("AWS_DEFAULT_ACL", default="private").strip() or None
AWS_QUERYSTRING_AUTH = env.bool("AWS_QUERYSTRING_AUTH", default=True)
AWS_S3_ADDRESSING_STYLE = env.str("AWS_S3_ADDRESSING_STYLE", default="virtual")
AWS_S3_SIGNATURE_VERSION = env.str("AWS_S3_SIGNATURE_VERSION", default="s3v4")
AWS_S3_FILE_OVERWRITE = env.bool("AWS_S3_FILE_OVERWRITE", default=False)
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": env.str("AWS_S3_CACHE_CONTROL", default="max-age=86400"),
}
# Base pública de MEDIA con S3 (opcional). Si vacío: CUSTOM_DOMAIN o patrón DigitalOcean Spaces.
DJANGO_S3_MEDIA_URL = env.str("DJANGO_S3_MEDIA_URL", default="").strip().rstrip("/")

if DJANGO_USE_S3_MEDIA:
    from django.core.exceptions import ImproperlyConfigured

    _s3_missing = [
        name
        for name, val in (
            ("AWS_ACCESS_KEY_ID", AWS_ACCESS_KEY_ID),
            ("AWS_SECRET_ACCESS_KEY", AWS_SECRET_ACCESS_KEY),
            ("AWS_STORAGE_BUCKET_NAME", AWS_STORAGE_BUCKET_NAME),
            ("AWS_S3_REGION_NAME", AWS_S3_REGION_NAME),
            ("AWS_S3_ENDPOINT_URL", AWS_S3_ENDPOINT_URL),
        )
        if not val
    ]
    if _s3_missing:
        raise ImproperlyConfigured(
            "DJANGO_USE_S3_MEDIA=1 requiere definir: " + ", ".join(_s3_missing)
        )

    if DJANGO_S3_MEDIA_URL:
        MEDIA_URL = DJANGO_S3_MEDIA_URL + "/"
    else:
        _domain = (AWS_S3_CUSTOM_DOMAIN or "").strip().strip("/")
        if _domain:
            MEDIA_URL = f"https://{_domain}/"
        else:
            MEDIA_URL = (
                f"https://{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com/"
            )

    STORAGES = {
        **STORAGES,
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
    }

# Correo (recibos, recordatorios). Toda la configuración sale del entorno / .env — ver .env.example
# - Preferido en DigitalOcean Droplet: BREVO_API_KEY (API HTTPS; no usa puertos SMTP bloqueados).
# - Si define EMAIL_HOST y no fuerza otro EMAIL_BACKEND, se usa SMTP (Gmail, etc.).
# - Sin EMAIL_HOST ni Brevo: QuietConsole (una línea en terminal, no llega al cliente).
# - EMAIL_FULL_CONSOLE=true: consola Django con MIME completo (PDF en base64).
# - EMAIL_USE_TLS y EMAIL_USE_SSL son mutuamente excluyentes en Django (465+SSL vs 587+TLS).
# - DEFAULT_FROM_EMAIL: si no lo define o deja el placeholder, se alinea con EMAIL_HOST_USER (recomendado en hosting).
# - ADMINS: opcional (ADMIN_EMAIL); avisos del sistema a usted, distintos del envío SMTP de recibos.


def _default_email_backend() -> str:
    _eb = env.str("EMAIL_BACKEND", default="").strip()
    if _eb:
        return _eb
    if env.str("EMAIL_FULL_CONSOLE", default="") == "1":
        return "django.core.mail.backends.console.EmailBackend"
    # Brevo por API HTTPS (recomendado en Droplets: DO bloquea 25/465/587).
    if env.str("BREVO_API_KEY", default="").strip():
        return "backend.brevo_backend.BrevoAPIEmailBackend"
    if env.str("EMAIL_HOST", default="").strip():
        return "django.core.mail.backends.smtp.EmailBackend"
    return "backend.mail_backends.QuietConsoleEmailBackend"


EMAIL_BACKEND = _default_email_backend()
EMAIL_HOST = env.str("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="").strip()
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")
# API key de Brevo (app.brevo.com → SMTP & API → API keys). Plan Free alcanza para recibos.
BREVO_API_KEY = env.str("BREVO_API_KEY", default="").strip()


def _solo_direccion_correo(valor: str) -> str:
    """Extrae correo@dominio de 'Nombre <correo@dominio>' o devuelve el string recortado."""
    s = (valor or "").strip()
    if not s:
        return ""
    m = re.search(r"<([^>]+)>", s)
    if m:
        return m.group(1).strip()
    return s


def _resolver_default_from_email() -> str:
    """Remitente de recibos: explícito en .env o alineado con la cuenta SMTP (evita rechazos del hosting)."""
    raw = env.str("DEFAULT_FROM_EMAIL", default="").strip()
    placeholder = "noreply@paredes.local"
    if raw and raw != placeholder:
        return raw
    if EMAIL_HOST_USER:
        nombre = env.str("DEFAULT_FROM_EMAIL_NAME", default="Paredes Desarrollos Inmobiliarios").strip()
        return f"{nombre} <{EMAIL_HOST_USER}>"
    return raw or placeholder


DEFAULT_FROM_EMAIL = _resolver_default_from_email()

# Origen técnico para mail_admins / errores (solo dirección, sin nombre para mostrar).
SERVER_EMAIL = (
    env.str("SERVER_EMAIL", default="").strip()
    or EMAIL_HOST_USER
    or _solo_direccion_correo(DEFAULT_FROM_EMAIL)
    or "noreply@paredes.local"
)

# Avisos del sistema (errores 500, etc.); no sustituye SMTP — solo define a quién notificar.
_admin_mail = env.str("ADMIN_EMAIL", default="").strip()
if _admin_mail:
    _admin_nombre = env.str("ADMIN_NAME", default="Administrador del sistema").strip()
    ADMINS = [(_admin_nombre, _admin_mail)]
    MANAGERS = ADMINS
else:
    ADMINS = []
    MANAGERS = []
RECIBO_ENVIAR_EMAIL = env.bool("RECIBO_ENVIAR_EMAIL", default=True)
# Si el cliente no tiene email, los recibos se envían a este correo (oficina / respaldo).
RECIBO_EMAIL_FALLBACK = env.str(
    "RECIBO_EMAIL_FALLBACK",
    default="paredesinmobi@gmail.com",
).strip()
# Nombre comercial en cuerpo/asunto de recibos y pies de mensaje WhatsApp (wa.me, Twilio, Meta).
RECIBO_NOTIFICACION_EMPRESA_NOMBRE = env.str(
    "RECIBO_NOTIFICACION_EMPRESA_NOMBRE",
    default="Paredes Desarrollos Inmobiliarios",
)
RECIBO_EMAIL_ASUNTO = env.str(
    "RECIBO_EMAIL_ASUNTO",
    default="Constancia de pago registrada — Paredes Desarrollos Inmobiliarios (PDF adjunto)",
)
# Vendedor: correo al pasar etapa comercial a «Cierre / venta» y al generar recibo de comisión (PDF adjunto).
VENDEDOR_NOTIFICAR_CIERRE_EMAIL = env.bool("VENDEDOR_NOTIFICAR_CIERRE_EMAIL", default=True)
VENDEDOR_NOTIFICAR_RECIBO_COMISION_EMAIL = env.bool(
    "VENDEDOR_NOTIFICAR_RECIBO_COMISION_EMAIL", default=True
)
VENDEDOR_CIERRE_EMAIL_ASUNTO = env.str(
    "VENDEDOR_CIERRE_EMAIL_ASUNTO",
    default="Etapa Cierre / venta — su contrato en el sistema",
)
VENDEDOR_RECIBO_COMISION_EMAIL_ASUNTO = env.str(
    "VENDEDOR_RECIBO_COMISION_EMAIL_ASUNTO",
    default="Recibo de comisión — PDF adjunto",
)
# Retenciones SV en recibo de comisión al vendedor (referencia operativa; no es asesoría fiscal).
COMISION_SV_RENTA_PCT = env.str("COMISION_SV_RENTA_PCT", default="10")
COMISION_SV_IVA_PCT = env.str("COMISION_SV_IVA_PCT", default="13")
COMISION_SV_IVA_RETENCION_PCT = env.str("COMISION_SV_IVA_RETENCION_PCT", default="1")
COMISION_SV_IVA_RETENCION_MIN = env.str("COMISION_SV_IVA_RETENCION_MIN", default="100")
COMISION_SV_RETENER_IVA_1PCT = env.bool("COMISION_SV_RETENER_IVA_1PCT", default=True)
# Prefijo telefónico para armar enlaces wa.me (El Salvador = 503)
RECIBO_WHATSAPP_PAIS = env.str("RECIBO_WHATSAPP_PAIS", default="503")
# URL pública HTTPS del sitio (sin barra final). Ej. https://ventas.suempresa.com
PUBLIC_BASE_URL = env.str("PUBLIC_BASE_URL", default="").rstrip("/")
# WhatsApp automático vía Twilio
RECIBO_ENVIAR_WHATSAPP_TWILIO = env.bool("RECIBO_ENVIAR_WHATSAPP_TWILIO", default=False)
TWILIO_ACCOUNT_SID = env.str("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = env.str("TWILIO_AUTH_TOKEN", default="")
TWILIO_WHATSAPP_FROM = env.str("TWILIO_WHATSAPP_FROM", default="")

# WhatsApp Cloud API (Meta)
WHATSAPP_CLOUD_ENABLED = env.bool("WHATSAPP_CLOUD_ENABLED", default=False)
WHATSAPP_CLOUD_ACCESS_TOKEN = env.str("WHATSAPP_CLOUD_ACCESS_TOKEN", default="")
WHATSAPP_CLOUD_PHONE_NUMBER_ID = env.str("WHATSAPP_CLOUD_PHONE_NUMBER_ID", default="")
WHATSAPP_CLOUD_API_VERSION = env.str("WHATSAPP_CLOUD_API_VERSION", default="v21.0")
WHATSAPP_WEBHOOK_VERIFY_TOKEN = env.str("WHATSAPP_WEBHOOK_VERIFY_TOKEN", default="")
RECIBO_ENVIAR_WHATSAPP_META = env.bool("RECIBO_ENVIAR_WHATSAPP_META", default=True)
# Formato de aceptación: envío automático al guardar (correo + WhatsApp Meta si aplica)
FORMATO_ACEPTACION_ENVIAR_AL_GUARDAR = env.bool("FORMATO_ACEPTACION_ENVIAR_AL_GUARDAR", default=True)
FORMATO_ACEPTACION_NOTIFICAR_CADA_GUARDADO = env.bool(
    "FORMATO_ACEPTACION_NOTIFICAR_CADA_GUARDADO", default=True
)
FORMATO_ACEPTACION_ENVIAR_EMAIL = env.bool("FORMATO_ACEPTACION_ENVIAR_EMAIL", default=True)
FORMATO_ACEPTACION_ENVIAR_WHATSAPP_META = env.bool(
    "FORMATO_ACEPTACION_ENVIAR_WHATSAPP_META", default=True
)
FORMATO_ACEPTACION_EMAIL_ASUNTO = env.str(
    "FORMATO_ACEPTACION_EMAIL_ASUNTO",
    default="Su formato de aceptación (PDF) — Paredes Bienes Raíces",
)
FORMATO_ACEPTACION_PROMESA_EMAIL_ASUNTO = env.str(
    "FORMATO_ACEPTACION_PROMESA_EMAIL_ASUNTO",
    default="Su promesa de venta escaneada — Paredes Bienes Raíces",
)
# Límite aproximado de documentos en WhatsApp Cloud API (PDF); evita subidas inútiles.
WHATSAPP_MAX_PDF_BYTES = env.int("WHATSAPP_MAX_PDF_BYTES", default=100 * 1024 * 1024)

# Promesa de venta (PDF): razón social que figura como promitente vendedor en el cuerpo del documento.
PBR_PROMESA_RAZON_SOCIAL_VENDEDOR = env.str(
    "PBR_PROMESA_RAZON_SOCIAL_VENDEDOR",
    default="PAREDES BIENES RAÍCES",
)
# Recibo / constancia de pago (PDF): NIT del emisor cuando deba figurar (opcional).
PBR_EMPRESA_NIT = env.str("PBR_EMPRESA_NIT", default="")
# Contacto fijo en encabezado del recibo digital (no el vendedor del contrato).
PBR_RECIBO_CONTACTO_NOMBRE = env.str(
    "PBR_RECIBO_CONTACTO_NOMBRE",
    default="Karen Patricia Vásquez Merlos",
)
# Dirección / teléfono en encabezado de recibos y formato de aceptación.
PBR_FORMATO_ACEPTACION_DIRECCION = env.str(
    "PBR_FORMATO_ACEPTACION_DIRECCION",
    default="16a Calle Oriente, Pol. C-1 #24, Col. El Molino, Distrito de San Miguel, San Miguel Centro, 7547-0186",
)

# Tras confirmar contraseña en /app/, cuántos segundos puede editar/eliminar sin volver a pedirla (no superusuarios).
PBR_SENSITIVE_REAUTH_TTL = env.int("PBR_SENSITIVE_REAUTH_TTL", default=900)

# Mapa catastral (Leaflet): capa Google opcional; si está vacío solo se usa OpenStreetMap.
GOOGLE_MAPS_API_KEY = env.str("GOOGLE_MAPS_API_KEY", default="").strip()

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/elegir/'
LOGOUT_REDIRECT_URL = '/login/'

# Sesiones: evita TypeError "datetime is not JSON serializable" al guardar la sesión.
SESSION_SERIALIZER = "backend.session.SafeJSONSerializer"
