"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import re
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Variables de entorno (.env en la raíz del proyecto). Ver .env.example
env = environ.Env(
    DEBUG=(bool, True),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_USE_SSL=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    "SECRET_KEY",
    default="django-insecure-(s#lp8&jfs)zgn9jfn05m_9aj5dtw2yns7%t3kgv6jv_cj1)&8",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=True)

# Auditoría por señales (crear/editar/borrar en modelos de negocio). Desactívela con AUDIT_SIGNALS_ENABLED=0 si no la necesita.
AUDIT_SIGNALS_ENABLED = env.bool("AUDIT_SIGNALS_ENABLED", default=True)

# En desarrollo permite acceder por localhost; en producción definir dominios reales.
ALLOWED_HOSTS = env.list(
    "DJANGO_ALLOWED_HOSTS",
    default=["127.0.0.1", "localhost", "[::1]"],
)

# HTTPS detrás de proxy (nginx, DigitalOcean App Platform, load balancer)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = env.bool("DJANGO_USE_X_FORWARDED_HOST", default=True)

# Orígenes confiables para CSRF con HTTPS (ej. https://tu-app.ondigitalocean.app)
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])

if not DEBUG:
    SESSION_COOKIE_SECURE = env.bool("DJANGO_SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = env.bool("DJANGO_CSRF_COOKIE_SECURE", default=True)
    SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=False)

# WhiteNoise: estáticos en producción tras collectstatic (DigitalOcean, etc.)
DJANGO_USE_WHITENOISE = env.bool("DJANGO_USE_WHITENOISE", default=not DEBUG)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'audit.apps.AuditConfig',
    'inmobiliaria.apps.InmobiliariaConfig',
    'crm.apps.CrmConfig',
    'docs.apps.DocsConfig',
    'usuarios.apps.UsuariosConfig',
]

def _build_middleware():
    mw = []
    if env.bool("PBR_URLCONF_PROBE", default=DEBUG):
        mw.append("core.middleware.UrlConfProbeMiddleware")
    mw.append("django.middleware.security.SecurityMiddleware")
    if DJANGO_USE_WHITENOISE:
        mw.append("whitenoise.middleware.WhiteNoiseMiddleware")
    mw.extend(
        [
            "django.contrib.sessions.middleware.SessionMiddleware",
            "django.middleware.common.CommonMiddleware",
            "django.middleware.csrf.CsrfViewMiddleware",
            "django.contrib.auth.middleware.AuthenticationMiddleware",
            "usuarios.middleware.AppUsuarioActivoMiddleware",
            "django.contrib.messages.middleware.MessageMiddleware",
            "django.middleware.clickjacking.XFrameOptionsMiddleware",
            "audit.middleware.AuditContextMiddleware",
        ]
    )
    return mw


MIDDLEWARE = _build_middleware()

ROOT_URLCONF = "backend.urls"

# Almacenamiento de archivos (media + estáticos recopilados)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage"
            if DJANGO_USE_WHITENOISE
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.perfil_app',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database — PostgreSQL
# Variables: POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_HOST, POSTGRES_PORT
# Crear la base antes: CREATE DATABASE nombre OWNER usuario ENCODING 'UTF8';
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_pg_options = {"connect_timeout": 10}
_postgres_sslmode = env.str("POSTGRES_SSLMODE", default="").strip()
if _postgres_sslmode:
    _pg_options["sslmode"] = _postgres_sslmode

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("POSTGRES_DB", default="paredes_bienes"),
        "USER": env.str("POSTGRES_USER", default="postgres"),
        "PASSWORD": env.str("POSTGRES_PASSWORD", default=""),
        "HOST": env.str("POSTGRES_HOST", default="localhost"),
        "PORT": env.str("POSTGRES_PORT", default="5432"),
        "OPTIONS": _pg_options,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-sv'

TIME_ZONE = 'America/El_Salvador'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# collectstatic → esta carpeta (producción + WhiteNoise)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media (PDFs emitidos)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Correo (recibos, recordatorios). Toda la configuración sale del entorno / .env — ver .env.example
# - Si define EMAIL_HOST y no fuerza otro EMAIL_BACKEND, se usa SMTP.
# - Sin EMAIL_HOST: QuietConsole (una línea en terminal, no llega al cliente).
# - EMAIL_FULL_CONSOLE=true: consola Django con MIME completo (PDF en base64).
# - EMAIL_USE_TLS y EMAIL_USE_SSL son mutuamente excluyentes en Django (465+SSL vs 587+TLS).
# - DEFAULT_FROM_EMAIL: si no lo define o deja el placeholder, se alinea con EMAIL_HOST_USER (recomendado en hosting).
# - ADMINS: opcional (ADMIN_EMAIL); avisos del sistema a usted, distintos del envío SMTP de recibos.


def _default_email_backend() -> str:
    _eb = env.str("EMAIL_BACKEND", default="").strip()
    if _eb:
        return _eb
    if env.str("EMAIL_FULL_CONSOLE", default="") == "1":
        return "django.core.mail.backends.console.EmailBackend"
    if env.str("EMAIL_HOST", default="").strip():
        return "django.core.mail.backends.smtp.EmailBackend"
    return "backend.mail_backends.QuietConsoleEmailBackend"


EMAIL_BACKEND = _default_email_backend()
EMAIL_HOST = env.str("EMAIL_HOST", default="")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)
EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="").strip()
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")


def _solo_direccion_correo(valor: str) -> str:
    """Extrae correo@dominio de 'Nombre <correo@dominio>' o devuelve el string recortado."""
    s = (valor or "").strip()
    if not s:
        return ""
    m = re.search(r"<([^>]+)>", s)
    if m:
        return m.group(1).strip()
    return s


def _resolver_default_from_email() -> str:
    """Remitente de recibos: explícito en .env o alineado con la cuenta SMTP (evita rechazos del hosting)."""
    raw = env.str("DEFAULT_FROM_EMAIL", default="").strip()
    placeholder = "noreply@paredes.local"
    if raw and raw != placeholder:
        return raw
    if EMAIL_HOST_USER:
        nombre = env.str("DEFAULT_FROM_EMAIL_NAME", default="Paredes Bienes Raíces").strip()
        return f"{nombre} <{EMAIL_HOST_USER}>"
    return raw or placeholder


DEFAULT_FROM_EMAIL = _resolver_default_from_email()

# Origen técnico para mail_admins / errores (solo dirección, sin nombre para mostrar).
SERVER_EMAIL = (
    env.str("SERVER_EMAIL", default="").strip()
    or EMAIL_HOST_USER
    or _solo_direccion_correo(DEFAULT_FROM_EMAIL)
    or "noreply@paredes.local"
)

# Avisos del sistema (errores 500, etc.); no sustituye SMTP — solo define a quién notificar.
_admin_mail = env.str("ADMIN_EMAIL", default="").strip()
if _admin_mail:
    _admin_nombre = env.str("ADMIN_NAME", default="Administrador del sistema").strip()
    ADMINS = [(_admin_nombre, _admin_mail)]
    MANAGERS = ADMINS
else:
    ADMINS = []
    MANAGERS = []
RECIBO_ENVIAR_EMAIL = env.bool("RECIBO_ENVIAR_EMAIL", default=True)
RECIBO_EMAIL_ASUNTO = env.str(
    "RECIBO_EMAIL_ASUNTO",
    default="Su recibo de pago — Paredes Bienes Raíces",
)
# Prefijo telefónico para armar enlaces wa.me (El Salvador = 503)
RECIBO_WHATSAPP_PAIS = env.str("RECIBO_WHATSAPP_PAIS", default="503")
# URL pública HTTPS del sitio (sin barra final). Ej. https://ventas.suempresa.com
PUBLIC_BASE_URL = env.str("PUBLIC_BASE_URL", default="").rstrip("/")
# WhatsApp automático vía Twilio
RECIBO_ENVIAR_WHATSAPP_TWILIO = env.bool("RECIBO_ENVIAR_WHATSAPP_TWILIO", default=False)
TWILIO_ACCOUNT_SID = env.str("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = env.str("TWILIO_AUTH_TOKEN", default="")
TWILIO_WHATSAPP_FROM = env.str("TWILIO_WHATSAPP_FROM", default="")

# WhatsApp Cloud API (Meta)
WHATSAPP_CLOUD_ENABLED = env.bool("WHATSAPP_CLOUD_ENABLED", default=False)
WHATSAPP_CLOUD_ACCESS_TOKEN = env.str("WHATSAPP_CLOUD_ACCESS_TOKEN", default="")
WHATSAPP_CLOUD_PHONE_NUMBER_ID = env.str("WHATSAPP_CLOUD_PHONE_NUMBER_ID", default="")
WHATSAPP_CLOUD_API_VERSION = env.str("WHATSAPP_CLOUD_API_VERSION", default="v21.0")
WHATSAPP_WEBHOOK_VERIFY_TOKEN = env.str("WHATSAPP_WEBHOOK_VERIFY_TOKEN", default="")
RECIBO_ENVIAR_WHATSAPP_META = env.bool("RECIBO_ENVIAR_WHATSAPP_META", default=False)
# Límite aproximado de documentos en WhatsApp Cloud API (PDF); evita subidas inútiles.
WHATSAPP_MAX_PDF_BYTES = env.int("WHATSAPP_MAX_PDF_BYTES", default=100 * 1024 * 1024)

# Promesa de venta (PDF): razón social que figura como promitente vendedor en el cuerpo del documento.
PBR_PROMESA_RAZON_SOCIAL_VENDEDOR = env.str(
    "PBR_PROMESA_RAZON_SOCIAL_VENDEDOR",
    default="PAREDES BIENES RAÍCES",
)
# Recibo / constancia de pago (PDF): NIT del emisor cuando deba figurar (opcional).
PBR_EMPRESA_NIT = env.str("PBR_EMPRESA_NIT", default="")

# Tras confirmar contraseña en /app/, cuántos segundos puede editar/eliminar sin volver a pedirla (no superusuarios).
PBR_SENSITIVE_REAUTH_TTL = env.int("PBR_SENSITIVE_REAUTH_TTL", default=900)

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Sesiones: evita TypeError "datetime is not JSON serializable" al guardar la sesión.
SESSION_SERIALIZER = "backend.session.SafeJSONSerializer"
