# Generated by Django 6.0.3 on 2026-03-26 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('inmobiliaria', '0002_inmueble_area_m2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelativoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROMESA_VENTA', 'Promesa de venta'), ('RECIBO_INGRESO', 'Recibo de ingreso'), ('HOJA_VISITA', 'Hoja de visita')], max_length=30)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Correlativo',
                'verbose_name_plural': 'Correlativos',
                'unique_together': {('tipo', 'anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROMESA_VENTA', 'Promesa de venta'), ('RECIBO_INGRESO', 'Recibo de ingreso'), ('HOJA_VISITA', 'Hoja de visita')], db_index=True, max_length=30)),
                ('numero', models.CharField(db_index=True, max_length=40)),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='docs/%Y/%m/')),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.contrato')),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hoja_visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.hojavisita')),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.inmueble')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lead')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.pago')),
            ],
            options={
                'verbose_name': 'Documento emitido',
                'verbose_name_plural': 'Documentos emitidos',
                'ordering': ['-emitido_en', '-id'],
            },
        ),
    ]
