# Generated by Django 6.0.3 on 2026-04-02 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
        ('inmobiliaria', '0015_vendedor_modulo_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoemitido',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_comision', to='inmobiliaria.vendedor', verbose_name='vendedor (comisión)'),
        ),
        migrations.AlterField(
            model_name='correlativodocumento',
            name='tipo',
            field=models.CharField(choices=[('PROMESA_VENTA', 'Promesa de venta'), ('RECIBO_INGRESO', 'Recibo de ingreso'), ('RECIBO_COMISION_VENDEDOR', 'Recibo de comisión (vendedor)'), ('HOJA_VISITA', 'Hoja de visita')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documentoemitido',
            name='tipo',
            field=models.CharField(choices=[('PROMESA_VENTA', 'Promesa de venta'), ('RECIBO_INGRESO', 'Recibo de ingreso'), ('RECIBO_COMISION_VENDEDOR', 'Recibo de comisión (vendedor)'), ('HOJA_VISITA', 'Hoja de visita')], db_index=True, max_length=30),
        ),
    ]
