# Generated by Django 6.0.3 on 2026-08-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_documentoemitido_asesor_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoemitido',
            name='comision_iva_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='IVA comisión (USD)'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='comision_neto_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe neto que recibe el vendedor tras retenciones.', max_digits=14, null=True, verbose_name='Neto a pagar comisión (USD)'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='comision_retencion_iva_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Retención IVA (USD)'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='comision_retencion_renta_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Retención renta (USD)'),
        ),
        migrations.AddField(
            model_name='documentoemitido',
            name='comision_tipo_persona',
            field=models.CharField(blank=True, help_text='NATURAL o CONTRIBUYENTE al momento de emitir el recibo.', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentoemitido',
            name='monto_comision_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión bruta (sin IVA) liquidada en el recibo al vendedor.', max_digits=14, null=True, verbose_name='Monto comisión (USD)'),
        ),
    ]
