# Generated by Django 6.0.3 on 2026-03-29 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador de sistema'), ('GERENCIA', 'Gerencia'), ('VENTAS', 'Ventas / comercial'), ('CARTERA', 'Cartera / finanzas'), ('PROYECTOS', 'Proyectos, lotes y mapa'), ('MARKETING', 'Marketing / CRM'), ('LECTURA', 'Solo consulta')], db_index=True, default='LECTURA', max_length=20, verbose_name='rol')),
                ('telefono', models.CharField(blank=True, max_length=40, verbose_name='teléfono')),
                ('activo_en_app', models.BooleanField(default=True, help_text='Si está desmarcado, no podrá usar /app/ (solo cerrar sesión).', verbose_name='activo en gestión web')),
                ('notas', models.TextField(blank=True, verbose_name='notas internas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_app', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario (app)',
                'verbose_name_plural': 'Perfiles de usuario (app)',
                'ordering': ['user__username'],
            },
        ),
    ]
