# Generated by Django 6.0.3 on 2026-03-26 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmobiliaria', '0002_inmueble_area_m2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fuente', models.CharField(blank=True, max_length=120)),
                ('estado_embudo', models.CharField(choices=[('INTERESADO', 'Interesado'), ('CITA_PROGRAMADA', 'Cita programada'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido')], db_index=True, default='INTERESADO', max_length=20)),
                ('proxima_accion_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_asignados', to=settings.AUTH_USER_MODEL)),
                ('inmueble_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='inmobiliaria.inmueble')),
                ('poligono_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='inmobiliaria.poligono')),
                ('proyecto_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='inmobiliaria.proyecto')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-creado_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HojaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('nombre_interesado', models.CharField(blank=True, max_length=160)),
                ('telefono_interesado', models.CharField(blank=True, max_length=40)),
                ('resultado', models.CharField(blank=True, max_length=240)),
                ('siguiente_paso', models.CharField(blank=True, max_length=240)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hojas_visita_creadas', to=settings.AUTH_USER_MODEL)),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='inmobiliaria.inmueble')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Hoja de visita',
                'verbose_name_plural': 'Hojas de visita',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Correo'), ('VISITA', 'Visita'), ('NOTA', 'Nota')], default='NOTA', max_length=12)),
                ('fecha', models.DateTimeField()),
                ('resumen', models.CharField(max_length=240)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_actividades_creadas', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
