# Generated by Django 6.0.3 on 2026-03-26 04:24

import django.core.validators
import django.db.models.deletion
import inmobiliaria.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('dui', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[inmobiliaria.validators.validar_dui_sv])),
                ('nit', models.CharField(blank=True, max_length=20, validators=[inmobiliaria.validators.validar_nit_sv])),
                ('pasaporte', models.CharField(blank=True, max_length=40)),
                ('direccion', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='ParametroMora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Default', max_length=80)),
                ('tasa_diaria_porcentaje', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Porcentaje diario sobre saldo vencido (ej. 0.05 = 0.05% diario).', max_digits=8)),
                ('dias_gracia', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parámetro de mora',
                'verbose_name_plural': 'Parámetros de mora',
            },
        ),
        migrations.CreateModel(
            name='Poligono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Polígono',
                'verbose_name_plural': 'Polígonos',
                'ordering': ['proyecto', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('departamento', models.CharField(blank=True, max_length=120)),
                ('direccion', models.TextField(blank=True)),
                ('permisos_notas', models.TextField(blank=True, help_text='Permisos, observaciones registrales, etc.')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOTE', 'Lote'), ('CASA_NUEVA', 'Casa nueva'), ('CASA_SEGUNDA', 'Casa segunda'), ('LOCAL', 'Local comercial')], default='LOTE', max_length=20)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido'), ('BLOQUEADO', 'Bloqueado')], default='DISPONIBLE', max_length=20)),
                ('codigo', models.CharField(db_index=True, help_text='Referencia interna (ej. A-15).', max_length=50)),
                ('precio_lista', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('area_varas_cuadradas', models.DecimalField(blank=True, decimal_places=4, help_text='Superficie en varas cuadradas (v²).', max_digits=12, null=True)),
                ('frente_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fondo_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('topografia', models.CharField(blank=True, max_length=200)),
                ('servicios_basicos', models.TextField(blank=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tour_virtual_url', models.URLField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('inmueble_padre', models.ForeignKey(blank=True, help_text='Lote padre si este es resultado de segregación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_segregados', to='inmobiliaria.inmueble')),
                ('poligono', models.ForeignKey(blank=True, help_text='Opcional: lotes dentro de un polígono.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='inmobiliaria.poligono')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='inmobiliaria.proyecto')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'ordering': ['proyecto', 'codigo'],
                'unique_together': {('proyecto', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha_firma', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('precio_final', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('plan_anos', models.PositiveSmallIntegerField(blank=True, choices=[(5, '5 años'), (10, '10 años'), (15, '15 años')], help_text='Plazo de financiamiento propio (años).', null=True)),
                ('tasa_interes_anual', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa anual para estimación de cuotas (parametrizable).', max_digits=6, null=True)),
                ('cuota_mensual_estimada', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('desglose_iva_monto', models.DecimalField(blank=True, decimal_places=2, help_text='IVA u otros impuestos desglosados (según asesoría contable).', max_digits=14, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='inmobiliaria.cliente')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='inmobiliaria.inmueble')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_firma', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='InmuebleImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inmobiliaria.inmueble')),
            ],
            options={
                'verbose_name': 'Imagen de inmueble',
                'verbose_name_plural': 'Imágenes de inmuebles',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(choices=[('PRIMA', 'Prima / enganche'), ('CUOTA', 'Cuota de financiamiento'), ('MANTENIMIENTO', 'Cuota de mantenimiento'), ('ABONO_CAPITAL', 'Abono a capital'), ('MORA', 'Intereses moratorios'), ('OTRO', 'Otro')], max_length=24)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inmobiliaria.contrato')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='poligono',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poligonos', to='inmobiliaria.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='poligono',
            unique_together={('proyecto', 'nombre')},
        ),
    ]
