# Generated by Django 6.0.3 on 2026-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Superficie en metros cuadrados (m²).', max_digits=12, null=True),
        ),
    ]
