# Generated by Django 6.0.3 on 2026-03-26 22:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_inmueble_area_m2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Número de cuota (1..N).')),
                ('vence_en', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida')], db_index=True, default='PENDIENTE', max_length=10)),
                ('pagado_en', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_programadas', to='inmobiliaria.contrato')),
                ('pago', models.ForeignKey(blank=True, help_text='Pago que liquidó esta cuota (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_aplicadas', to='inmobiliaria.pago')),
            ],
            options={
                'verbose_name': 'Cuota programada',
                'verbose_name_plural': 'Cuotas programadas',
                'ordering': ['contrato', 'numero'],
                'unique_together': {('contrato', 'numero')},
            },
        ),
    ]
