# Generated by Django 6.0.3 on 2026-03-26 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0003_cuotaprogramada'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('EMAIL', 'Correo'), ('WHATSAPP_MANUAL', 'WhatsApp (manual)')], max_length=20)),
                ('programado_para', models.DateField(help_text='Fecha objetivo del recordatorio.')),
                ('mensaje', models.TextField(blank=True)),
                ('wa_link', models.URLField(blank=True)),
                ('enviado', models.BooleanField(default=False)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='inmobiliaria.cuotaprogramada')),
            ],
            options={
                'verbose_name': 'Recordatorio de pago',
                'verbose_name_plural': 'Recordatorios de pago',
                'ordering': ['-programado_para', '-id'],
                'unique_together': {('cuota', 'canal', 'programado_para')},
            },
        ),
    ]
