# Generated by Django 6.0.3 on 2026-03-26 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0004_recordatoriopago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='comision_monto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto fijo de comisión (opcional). Si rellena ambos, use el criterio que defina la empresa.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='comision_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de comisión sobre el precio final (opcional).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='etapa_comercial',
            field=models.CharField(choices=[('CONVERSACION', 'En conversación'), ('RESERVA', 'Reserva / apartado'), ('DOCUMENTOS', 'Documentación'), ('CIERRE', 'Cierre / venta')], db_index=True, default='CONVERSACION', help_text='Etapa en el embudo de ventas.', max_length=20),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Usuario interno asignado (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_como_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vendedor_nombre',
            field=models.CharField(blank=True, help_text='Nombre del vendedor si no es usuario del sistema.', max_length=120),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='cliente_reserva',
            field=models.ForeignKey(blank=True, help_text='Cliente que tiene el lote apartado (solo si está reservado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles_reservados', to='inmobiliaria.cliente'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='reserva_hasta',
            field=models.DateField(blank=True, help_text='Fecha límite de la reserva. Pasada esa fecha, ejecute el comando expirar_reservas o revierta manualmente.', null=True),
        ),
        migrations.CreateModel(
            name='HistorialPrecioInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='inmobiliaria.inmueble')),
            ],
            options={
                'verbose_name': 'Historial de precio',
                'verbose_name_plural': 'Historial de precios',
                'ordering': ['-creado_en'],
            },
        ),
    ]
