# Generated by Django 6.0.3 on 2026-03-26 23:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0005_reservas_embudo_comisiones_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poligono',
            name='plano',
            field=models.FileField(blank=True, help_text='Foto o PDF del plano del polígono (JPG, PNG, WEBP o PDF).', upload_to='poligonos/planos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'], message='Use PDF, JPG, PNG o WEBP.')]),
        ),
    ]
