# Generated by Django 6.0.3 on 2026-03-26 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0006_poligono_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poligono',
            name='plano',
            field=models.FileField(blank=True, help_text='Suba una foto o un PDF escaneado del plano catastral o de lotificación.', upload_to='poligonos/planos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'], message='Use PDF, JPG, PNG o WEBP.')], verbose_name='Plano (foto o PDF)'),
        ),
    ]
