# Generated by Django 6.0.3 on 2026-03-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0007_alter_poligono_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='poligono',
            name='recorte_alto_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alto del rectángulo (0–100).', max_digits=5, null=True, verbose_name='Recorte: alto visible (%)'),
        ),
        migrations.AddField(
            model_name='poligono',
            name='recorte_ancho_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ancho del rectángulo que corresponde a este polígono (0–100).', max_digits=5, null=True, verbose_name='Recorte: ancho visible (%)'),
        ),
        migrations.AddField(
            model_name='poligono',
            name='recorte_izq_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia desde el borde izquierdo de la imagen hasta donde empieza la zona de este polígono (0–100).', max_digits=5, null=True, verbose_name='Recorte: desde la izquierda (%)'),
        ),
        migrations.AddField(
            model_name='poligono',
            name='recorte_sup_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia desde el borde superior (0–100).', max_digits=5, null=True, verbose_name='Recorte: desde arriba (%)'),
        ),
    ]
