# Generated by Django 6.0.3 on 2026-03-27 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0008_poligono_recorte_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='plano_maestro',
            field=models.FileField(blank=True, help_text='Una sola imagen o PDF del plano completo de la lotificación. Cada polígono marcará su zona sobre este archivo (sin volver a subirlo).', upload_to='proyectos/planos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'], message='Use PDF, JPG, PNG o WEBP.')], verbose_name='Plano maestro del proyecto'),
        ),
        migrations.AlterField(
            model_name='poligono',
            name='plano',
            field=models.FileField(blank=True, help_text='Solo si este polígono usa otro archivo distinto al plano maestro del proyecto. Si lo deja vacío, se usa el plano del proyecto.', upload_to='poligonos/planos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'], message='Use PDF, JPG, PNG o WEBP.')], verbose_name='Plano propio (opcional)'),
        ),
    ]
