# Generated by Django 6.0.3 on 2026-03-28 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0013_clientedocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuotas_incluidas',
            field=models.PositiveSmallIntegerField(default=1, help_text='Si el concepto es cuota de financiamiento: cuántas cuotas consecutivas (en orden de vencimiento) liquida este pago.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
