# Generated by Django 6.0.3 on 2026-04-02 20:00

import django.core.validators
import django.db.models.deletion
import inmobiliaria.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0014_pago_cuotas_incluidas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Usuario interno (se sincroniza si el vendedor tiene vínculo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_como_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vendedor_nombre',
            field=models.CharField(blank=True, help_text='Texto libre si no usa el catálogo o como respaldo en documentos.', max_length=120),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('dui', models.CharField(blank=True, max_length=20, validators=[inmobiliaria.validators.validar_dui_sv])),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('porcentaje_comision_default', models.DecimalField(decimal_places=2, default=Decimal('3'), help_text='Porcentaje sugerido sobre el precio de venta al elegir este vendedor en un contrato.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario_vinculo', models.ForeignKey(blank=True, help_text='Usuario interno opcional si el vendedor tiene cuenta en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor_catalogo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='vendedor_perfil',
            field=models.ForeignKey(blank=True, help_text='Vendedor del módulo de ventas; define comisión sugerida y recibo de comisión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='inmobiliaria.vendedor', verbose_name='Vendedor (catálogo)'),
        ),
    ]
