# Generated by Django 6.0.3 on 2026-04-04 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0016_inmueble_geometria_catastral_geojson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoAceptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_formulario', models.PositiveIntegerField(db_index=True, editable=False, unique=True, verbose_name='Nº formulario')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('lugar_fecha_nacimiento', models.CharField(blank=True, max_length=200, verbose_name='Lugar y fecha de nacimiento')),
                ('dui_numero', models.CharField(blank=True, max_length=30, verbose_name='No. DUI')),
                ('dui_exp_lugar_fecha', models.CharField(blank=True, max_length=120, verbose_name='Lugar / fecha exp. DUI')),
                ('nit_numero', models.CharField(blank=True, max_length=30, verbose_name='NIT')),
                ('direccion_domicilio', models.TextField(blank=True, verbose_name='Dirección de domicilio')),
                ('telefono_domicilio', models.CharField(blank=True, max_length=40, verbose_name='Teléfono (domicilio)')),
                ('direccion_notificacion', models.TextField(blank=True, verbose_name='Dirección para notificación')),
                ('telefono_notificacion', models.CharField(blank=True, max_length=40, verbose_name='Teléfono (notificación)')),
                ('trabaja_lo_propio', models.CharField(blank=True, max_length=200, verbose_name='Trabaja en lo propio')),
                ('nombre_empresa_trabajo', models.CharField(blank=True, max_length=200, verbose_name='Nombre de la empresa donde trabaja')),
                ('direccion_trabajo', models.TextField(blank=True, verbose_name='Dirección / trabajo')),
                ('telefono_trabajo', models.CharField(blank=True, max_length=40, verbose_name='Teléfono (trabajo)')),
                ('cargo', models.CharField(blank=True, max_length=120, verbose_name='Cargo que desempeña')),
                ('sueldo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Sueldo $')),
                ('num_familia_grupo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. personas del grupo familiar')),
                ('num_personas_trabajan', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. personas que trabajan')),
                ('num_personas_estudian', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. personas que estudian')),
                ('ref_com_nombre_1', models.CharField(blank=True, max_length=200, verbose_name='Ref. comercial — empresa 1')),
                ('ref_com_tel_1', models.CharField(blank=True, max_length=40, verbose_name='Ref. comercial — tel. 1')),
                ('ref_com_obs_1', models.CharField(blank=True, max_length=200, verbose_name='Ref. comercial — observación 1')),
                ('ref_com_nombre_2', models.CharField(blank=True, max_length=200, verbose_name='Ref. comercial — empresa 2')),
                ('ref_com_tel_2', models.CharField(blank=True, max_length=40, verbose_name='Ref. comercial — tel. 2')),
                ('ref_com_obs_2', models.CharField(blank=True, max_length=200, verbose_name='Ref. comercial — observación 2')),
                ('ref_per_nombre_1', models.CharField(blank=True, max_length=200, verbose_name='Ref. personal — nombre 1')),
                ('ref_per_tel_1', models.CharField(blank=True, max_length=40, verbose_name='Ref. personal — tel. 1')),
                ('ref_per_obs_1', models.CharField(blank=True, max_length=200, verbose_name='Ref. personal — observación 1')),
                ('ref_per_nombre_2', models.CharField(blank=True, max_length=200, verbose_name='Ref. personal — nombre 2')),
                ('ref_per_tel_2', models.CharField(blank=True, max_length=40, verbose_name='Ref. personal — tel. 2')),
                ('ref_per_obs_2', models.CharField(blank=True, max_length=200, verbose_name='Ref. personal — observación 2')),
                ('nombre_proyecto', models.CharField(blank=True, max_length=200, verbose_name='Nombre del proyecto')),
                ('direccion_terreno', models.TextField(blank=True, verbose_name='Dirección (terreno)')),
                ('num_lote', models.CharField(blank=True, max_length=80, verbose_name='No. de lote')),
                ('poligono_txt', models.CharField(blank=True, max_length=120, verbose_name='Polígono')),
                ('area_m2_txt', models.CharField(blank=True, max_length=40, verbose_name='Área m²')),
                ('area_v2_txt', models.CharField(blank=True, max_length=40, verbose_name='Área v²')),
                ('prima_1', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Prima 1 $')),
                ('valor_inmueble', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor del inmueble')),
                ('prima_2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Prima 2 $')),
                ('valor_financiamiento', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor del financiamiento')),
                ('letra_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Letra mensual')),
                ('plazo_txt', models.CharField(blank=True, max_length=80, verbose_name='Plazo')),
                ('num_cuota_txt', models.CharField(blank=True, max_length=40, verbose_name='No. cuota')),
                ('interes_txt', models.CharField(blank=True, max_length=80, verbose_name='Interés')),
                ('fecha_primera_cuota', models.DateField(blank=True, null=True, verbose_name='Fecha pago primera cuota')),
                ('fecha_pago_mensual', models.CharField(blank=True, max_length=80, verbose_name='Fecha de pago mensual')),
                ('lugar_pago', models.CharField(blank=True, max_length=200, verbose_name='Lugar de pago')),
                ('ben_nombre_1', models.CharField(blank=True, max_length=200, verbose_name='Beneficiario 1 — nombre')),
                ('ben_parentesco_1', models.CharField(blank=True, max_length=80, verbose_name='Beneficiario 1 — parentesco')),
                ('ben_nombre_2', models.CharField(blank=True, max_length=200, verbose_name='Beneficiario 2 — nombre')),
                ('ben_parentesco_2', models.CharField(blank=True, max_length=80, verbose_name='Beneficiario 2 — parentesco')),
                ('elaborado_por', models.CharField(blank=True, max_length=120, verbose_name='Elaborado por')),
                ('lugar_y_fecha', models.CharField(blank=True, max_length=200, verbose_name='Lugar y fecha')),
                ('firma_aceptante', models.ImageField(blank=True, upload_to='formatos_aceptacion/firmas/%Y/%m/', verbose_name='Firma aceptante (cliente)')),
                ('firma_vendedor', models.ImageField(blank=True, upload_to='formatos_aceptacion/firmas/%Y/%m/', verbose_name='Firma vendedor')),
                ('firma_autorizado', models.ImageField(blank=True, upload_to='formatos_aceptacion/firmas/%Y/%m/', verbose_name='Firma autorizado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formato_aceptacion', to='inmobiliaria.contrato')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_aceptacion_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formato de aceptación',
                'verbose_name_plural': 'Formatos de aceptación',
                'ordering': ['-numero_formulario'],
            },
        ),
    ]
