# Generated by Django 6.0.3 on 2026-04-04 03:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0021_formato_nacimiento_dui_exp_separados'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoaceptacion',
            name='ben_porcentaje_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Beneficiario 1 — %'),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='ben_porcentaje_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Beneficiario 2 — %'),
        ),
    ]
