# Generated by Django 6.0.3 on 2026-04-04 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0023_pago_formato_aceptacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoaceptacion',
            name='promesa_venta_escaneada',
            field=models.FileField(blank=True, upload_to='formatos_aceptacion/promesas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'], message='Use PDF, JPG o PNG.')], verbose_name='Promesa de venta escaneada'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuotas_incluidas',
            field=models.PositiveSmallIntegerField(default=1, help_text='Si el concepto es cuota de financiamiento: cuántas cuotas consecutivas (en orden de vencimiento) liquida este pago.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
