# Generated by Django 6.0.3 on 2026-04-04 20:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0024_formato_aceptacion_promesa_escaneada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametromora',
            name='dias_gracia',
            field=models.PositiveSmallIntegerField(default=0, help_text='Días naturales después del vencimiento de la cuota (día acordado en formato de aceptación / calendario de cuotas) antes de aplicar mora según esta tasa.'),
        ),
        migrations.AlterField(
            model_name='parametromora',
            name='tasa_diaria_porcentaje',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Porcentaje diario sobre saldo vencido (ej. 0.05 = 0.05% diario). El saldo vencido se entiende respecto a la fecha de vencimiento de cada cuota del contrato; ese vencimiento debe coincidir con el calendario generado desde el formato de aceptación (mismo día de cada mes hasta la última cuota).', max_digits=8),
        ),
    ]
