# Generated by Django 6.0.3 on 2026-04-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0025_parametro_mora_help_text_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoaceptacion',
            name='observaciones_financiamiento',
            field=models.TextField(blank=True, help_text='Detalles especiales. Frases como «sin interés», «0 %» o «10 años» pueden completar plazo o interés si esos campos están vacíos al guardar.', verbose_name='Observaciones (financiamiento)'),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='prima_1_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha prima 1'),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='prima_2_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha prima 2'),
        ),
    ]
