# Generated by Django 6.0.3 on 2026-04-05 04:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0026_formato_primas_fechas_obs_financiamiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmuebleimagen',
            options={'ordering': ['-es_portada', 'orden', 'id'], 'verbose_name': 'Imagen de inmueble', 'verbose_name_plural': 'Imágenes de inmuebles'},
        ),
        migrations.AddField(
            model_name='inmuebleimagen',
            name='es_portada',
            field=models.BooleanField(default=False, verbose_name='Imagen principal (catálogo)'),
        ),
        migrations.AddField(
            model_name='inmuebleimagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='inmuebles/galeria/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'], message='Use PNG, JPG, JPEG o WEBP.')]),
        ),
        migrations.AlterField(
            model_name='inmuebleimagen',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InmuebleDetalleEdificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitaciones', models.PositiveSmallIntegerField(blank=True, help_text='Solo vivienda.', null=True, verbose_name='Habitaciones')),
                ('banos', models.DecimalField(blank=True, decimal_places=1, help_text='Ej. 2.5 (casa o local).', max_digits=4, null=True, verbose_name='Baños')),
                ('niveles', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Niveles / plantas')),
                ('amueblada', models.BooleanField(default=False, help_text='Vivienda amueblada.', verbose_name='Amueblada')),
                ('cochera_cubiertas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cochera (espacios cubiertos)')),
                ('area_construccion_m2', models.DecimalField(blank=True, decimal_places=2, help_text='Distinto del área de terreno (lote).', max_digits=12, null=True, verbose_name='Metros cuadrados de construcción')),
                ('seguridad', models.TextField(blank=True, help_text='Ej. vigilancia, cerco, alarmas (local comercial).', verbose_name='Seguridad')),
                ('parqueos_clientes', models.PositiveSmallIntegerField(blank=True, help_text='Local comercial.', null=True, verbose_name='Parqueos para clientes')),
                ('carga_electrica', models.CharField(blank=True, help_text='Ej. trifásica, 200 A, etc.', max_length=200, verbose_name='Carga eléctrica / instalación')),
                ('inmueble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_edificacion', to='inmobiliaria.inmueble')),
            ],
            options={
                'verbose_name': 'Detalle construcción / local',
                'verbose_name_plural': 'Detalles construcción / local',
            },
        ),
    ]
