# Generated by Django 6.0.3 on 2026-04-06 01:25

import django.core.validators
import django.db.models.deletion
import inmobiliaria.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0026_formato_primas_fechas_obs_financiamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebleimagen',
            name='es_portada',
            field=models.BooleanField(default=False, verbose_name='Portada'),
        ),
        migrations.AddField(
            model_name='inmuebleimagen',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='inmuebles/galeria/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp', 'gif'], message='Use PNG, JPG, JPEG, WEBP o GIF.')], verbose_name='Archivo de imagen'),
        ),
        migrations.AlterField(
            model_name='inmuebleimagen',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='InmuebleDetalleCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_construccion', models.CharField(blank=True, choices=[('SISTEMA_BLOQUE', 'Sistema bloque'), ('PREFABRICADA', 'Prefabricada'), ('ADOBE_REFORZADO', 'Adobe reforzado')], max_length=24, verbose_name='Tipo de construcción')),
                ('niveles', models.PositiveSmallIntegerField(blank=True, help_text='1, 2 o 3 plantas.', null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Niveles (plantas)')),
                ('distribucion_sala_comedor_cocina', models.CharField(blank=True, choices=[('INDEPENDIENTES', 'Independientes'), ('CONCEPTO_ABIERTO', 'Concepto abierto'), ('MIXTO', 'Mixto / otro (amplíe en notas)')], help_text='¿Independientes o concepto abierto?', max_length=24, verbose_name='Sala, comedor y cocina')),
                ('habitaciones', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de habitaciones')),
                ('banos', models.DecimalField(blank=True, decimal_places=1, help_text='Ej. 2 o 2,5.', max_digits=4, null=True, verbose_name='Número de baños')),
                ('cochera_capacidad_vehiculos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cochera: capacidad (vehículos)')),
                ('cochera_techada', models.BooleanField(default=False, verbose_name='Cochera techada')),
                ('area_construccion_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Área de construcción (m²)')),
                ('modelo_casa', models.CharField(blank=True, help_text='Ej. «Modelo Roble», «Modelo Gardenia».', max_length=120, verbose_name='Modelo de casa')),
                ('ano_finalizacion_obra', models.PositiveSmallIntegerField(blank=True, help_text='Cuándo se entrega o entregó la obra (casa nueva).', null=True, verbose_name='Año de finalización de la obra')),
                ('garantia_construccion', models.TextField(blank=True, help_text='Ej. 1 año en vicios ocultos, 5 años en estructura.', verbose_name='Garantía de construcción')),
                ('extras_incluidos', models.TextField(blank=True, help_text='Ej. piso cerámico, encimeras de granito, closets.', verbose_name='Extras incluidos')),
                ('conexiones_ac_calentador', models.TextField(blank=True, help_text='Si ya tiene acometida u observaciones.', verbose_name='Conexiones (aire acondicionado / calentador)')),
                ('edad_construccion_anios', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Edad de la construcción (años, aprox.)')),
                ('estado_conservacion', models.CharField(blank=True, choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REQUIERE_REPARACIONES', 'Requiere reparaciones')], max_length=24, verbose_name='Estado de conservación')),
                ('remodelaciones_recientes', models.TextField(blank=True, help_text='Ej. «Techo cambiado en 2024», «Piso nuevo».', verbose_name='Remodelaciones recientes')),
                ('gravamenes_hipoteca', models.TextField(blank=True, help_text='¿Hipoteca vigente con algún banco? (relevante para compraventa).', verbose_name='Gravámenes / hipoteca')),
                ('servicio_anda_al_dia', models.BooleanField(default=False, verbose_name='Servicio de agua (ANDA) al día')),
                ('servicio_eeh_al_dia', models.BooleanField(default=False, verbose_name='Energía eléctrica (EEH/DELSUR) al día')),
                ('servicio_alcaldia_al_dia', models.BooleanField(default=False, verbose_name='Impuestos municipales (Alcaldía) al día')),
                ('escritura_copia', models.FileField(blank=True, help_text='Para validar matrícula en CNR.', upload_to='inmuebles/casas/escritura/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'], message='Use PDF o imagen (JPG, PNG, WEBP).')], verbose_name='Escritura (copia simple)')),
                ('dui_dueno', models.CharField(blank=True, help_text='Para formato de aceptación y trámites.', max_length=20, validators=[inmobiliaria.validators.validar_dui_sv], verbose_name='DUI del dueño')),
                ('recibo_luz_agua', models.FileField(blank=True, help_text='Verificar dirección y ausencia de mora.', upload_to='inmuebles/casas/recibos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'], message='Use PDF o imagen.')], verbose_name='Recibo de luz y/o agua')),
                ('plano_catastro', models.FileField(blank=True, help_text='Ayuda a la valuación bancaria.', upload_to='inmuebles/casas/catastro/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'], message='Use PDF o imagen.')], verbose_name='Plano de catastro')),
                ('inmueble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_casa', to='inmobiliaria.inmueble', verbose_name='Inmueble')),
            ],
            options={
                'verbose_name': 'Detalle de casa (venta)',
                'verbose_name_plural': 'Detalles de casas (venta)',
            },
        ),
    ]
