# Generated by Django 6.0.3 on 2026-04-05 04:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def forwards_backfill_modo(apps, schema_editor):
    Inmueble = apps.get_model("inmobiliaria", "Inmueble")
    for row in Inmueble.objects.all().only("id", "tipo", "modo_catalogo"):
        t = row.tipo
        if t == "LOTE":
            row.modo_catalogo = "LOTIFICACION"
        elif t in ("CASA_NUEVA", "CASA_SEGUNDA"):
            row.modo_catalogo = "CASA"
        else:
            row.modo_catalogo = "ALQUILER"
        row.save(update_fields=["modo_catalogo"])


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0027_inmueble_detalle_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='deposito_alquiler',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Depósito / garantía ($)'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='modo_catalogo',
            field=models.CharField(choices=[('LOTIFICACION', 'Lotificación (lote en proyecto)'), ('CASA', 'Casa (venta)'), ('ALQUILER', 'Alquiler')], default='LOTIFICACION', help_text='Elija primero el tipo de operación; el formulario mostrará las secciones correspondientes.', max_length=20, verbose_name='¿Qué está registrando?'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio_alquiler_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo si el inmueble es para alquiler.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Canon de alquiler mensual ($)'),
        ),
        migrations.RunPython(forwards_backfill_modo, migrations.RunPython.noop),
    ]
