# Generated by Django 6.0.3 on 2026-04-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0027_inmueble_casa_detalle_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='aire_ac_cantidad',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de unidades instaladas (vacío si no aplica).', null=True, verbose_name='Cantidad de aires acondicionados'),
        ),
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='aire_ac_ubicacion',
            field=models.TextField(blank=True, help_text='Ej. habitaciones, sala, comedor.', verbose_name='Ubicación de los aires acondicionados'),
        ),
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='amueblada',
            field=models.BooleanField(default=False, verbose_name='Amueblada'),
        ),
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='direccion_dueno',
            field=models.TextField(blank=True, verbose_name='Dirección del dueño'),
        ),
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='direccion_exacta',
            field=models.TextField(blank=True, help_text='Dirección completa para ubicar la propiedad.', verbose_name='Dirección exacta del inmueble'),
        ),
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='medios_pago_dueno',
            field=models.TextField(blank=True, help_text='Ej. solo efectivo, Fondo Social, acuerdo con banco.', verbose_name='Medios de pago que acepta el dueño'),
        ),
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='muebles_incluidos',
            field=models.TextField(blank=True, help_text='Si está amueblada, indique con qué muebles se entrega.', verbose_name='Muebles incluidos (inventario)'),
        ),
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='telefono_dueno',
            field=models.CharField(blank=True, max_length=40, verbose_name='Teléfono del dueño'),
        ),
    ]
