# Generated by Django 6.0.3 on 2026-04-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0028_detalle_casa_direccion_amueblada_dueno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmuebledetallecasa',
            name='medios_pago_dueno',
        ),
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='pago_dueno_efectivo',
            field=models.BooleanField(default=False, help_text='El dueño acepta pago en efectivo.', verbose_name='Efectivo'),
        ),
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='pago_dueno_fondo_social',
            field=models.BooleanField(default=False, verbose_name='Financiamiento con Fondo Social'),
        ),
        migrations.AddField(
            model_name='inmuebledetallecasa',
            name='pago_dueno_sistema_financiero',
            field=models.BooleanField(default=False, help_text='El dueño acepta trato o financiamiento vía banco.', verbose_name='Sistema financiero (banco)'),
        ),
    ]
