# Generated by Django 6.0.3 on 2026-04-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0029_detalle_casa_pago_dueno_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='en_alquiler',
            field=models.BooleanField(default=False, help_text='Si está marcado, el inmueble aparece en Arrendamientos (locales o casas según el tipo).', verbose_name='En alquiler'),
        ),
    ]
