# Generated by Django 6.0.3 on 2026-04-06 03:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0030_inmueble_en_alquiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='InmuebleDetalleLocalAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renta_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Ej. $500.00.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto de renta mensual')),
                ('cuota_mantenimiento', models.DecimalField(blank=True, decimal_places=2, help_text='Si el local está en una plaza.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cuota de mantenimiento / vigilancia')),
                ('deposito_garantia', models.DecimalField(blank=True, decimal_places=2, help_text='Suele equivaler a un mes de renta.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Depósito en garantía')),
                ('uso_permitido', models.TextField(blank=True, help_text='Ej. oficina, restaurante, clínica. Vital en San Miguel para no saturar una plaza con el mismo rubro.', verbose_name='Uso permitido')),
                ('plazo_contrato', models.CharField(blank=True, help_text='Ej. mínimo 1 año o 12 meses.', max_length=200, verbose_name='Plazo del contrato')),
                ('incremento_anual_pct', models.DecimalField(blank=True, decimal_places=2, help_text='En El Salvador suele estilarse 5 % o 10 % cada año.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Incremento anual (%)')),
                ('periodo_gracia_dias', models.PositiveSmallIntegerField(blank=True, help_text='Días sin cobrar renta para remodelar u otros acuerdos.', null=True, verbose_name='Período de gracia (días)')),
                ('inmueble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_local_alquiler', to='inmobiliaria.inmueble', verbose_name='Inmueble')),
            ],
            options={
                'verbose_name': 'Detalle local en alquiler',
                'verbose_name_plural': 'Detalles locales en alquiler',
            },
        ),
    ]
