# Generated by Django 6.0.3 on 2026-04-06 03:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0031_inmueble_detalle_local_alquiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='InmuebleDetalleCasaAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_detallado_estado', models.TextField(blank=True, help_text='Ej. bomba de agua, calentador, lámparas: indique estado (funcionando, nueva, etc.).', verbose_name='Inventario detallado y estado')),
                ('acepta_mascotas', models.BooleanField(default=False, verbose_name='Se aceptan mascotas')),
                ('maximo_personas', models.PositiveSmallIntegerField(blank=True, help_text='Cupos permitidos; vacío si no aplica límite explícito.', null=True, verbose_name='Máximo de personas')),
                ('uso_exclusivo_habitacional', models.BooleanField(default=False, verbose_name='Uso exclusivo habitacional')),
                ('servicios_incluidos_renta', models.TextField(blank=True, help_text='Ej. vigilancia, internet, agua; relevante para el recibo mensual.', verbose_name='Servicios incluidos en la renta')),
                ('arrendamiento_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Ej. $450.00.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Arrendamiento mensual')),
                ('deposito_garantia_monto', models.DecimalField(blank=True, decimal_places=2, help_text='No es renta: fianza o mes adelantado en garantía.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Depósito (fondo en garantía)')),
                ('vigencia_inicio', models.DateField(blank=True, null=True, verbose_name='Vigencia: fecha de inicio')),
                ('vigencia_fin', models.DateField(blank=True, help_text='Ej. contrato 12 meses forzosos hasta esta fecha.', null=True, verbose_name='Vigencia: fecha de fin')),
                ('inmueble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_casa_alquiler', to='inmobiliaria.inmueble', verbose_name='Inmueble')),
            ],
            options={
                'verbose_name': 'Detalle casa en alquiler',
                'verbose_name_plural': 'Detalles casas en alquiler',
            },
        ),
    ]
