# Generated by Django 6.0.3 on 2026-06-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0032_inmueble_detalle_casa_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebledetallecasaalquiler',
            name='inquilino',
            field=models.ForeignKey(blank=True, help_text='Cliente al que se arrienda esta casa (módulo alquiler, aparte de contratos de venta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres_casa', to='inmobiliaria.cliente', verbose_name='Inquilino / arrendatario'),
        ),
        migrations.AddField(
            model_name='inmuebledetallelocalalquiler',
            name='inquilino',
            field=models.ForeignKey(blank=True, help_text='Cliente al que se arrienda este local (módulo alquiler, aparte de contratos de venta).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres_local', to='inmobiliaria.cliente', verbose_name='Inquilino / arrendatario'),
        ),
    ]
