# Generated by Django 6.0.3 on 2026-07-27 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0038_proyecto_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoaceptacion',
            name='boucher_pago_reserva',
            field=models.FileField(blank=True, upload_to='formatos_aceptacion/vouchers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Use PDF, JPG o PNG.')], verbose_name='Boucher de pago de reserva'),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='dui_cliente_archivo',
            field=models.FileField(blank=True, upload_to='formatos_aceptacion/dui/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='El DUI debe ser un archivo PDF.')], verbose_name='DUI del cliente (frente y reverso)'),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='formato_aceptacion_fisico',
            field=models.FileField(blank=True, upload_to='formatos_aceptacion/fisico/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'], message='Use PDF o JPG.')], verbose_name='Formato de aceptación en físico'),
        ),
    ]
