# Generated by Django 6.0.3 on 2026-07-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0039_formato_aceptacion_documentos_adjuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoaceptacion',
            name='tipo_financiamiento',
            field=models.CharField(
                blank=True,
                choices=[
                    ('A_PLAZOS', 'Con Financiamiento (A Plazos)'),
                    ('CONTADO', 'Contado'),
                ],
                db_index=True,
                default='A_PLAZOS',
                help_text='Con financiamiento a plazos o pago de contado.',
                max_length=20,
                verbose_name='Tipo de financiamiento',
            ),
        ),
    ]
