# Generated by Django 6.0.3 on 2026-07-27 03:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0040_formato_aceptacion_tipo_financiamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoaceptacion',
            name='boucher_pago_reserva',
            field=models.FileField(blank=True, upload_to='formatos_aceptacion/vouchers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Use PDF, JPG o PNG.')], verbose_name='Voucher de Reserva'),
        ),
        migrations.AlterField(
            model_name='formatoaceptacion',
            name='formato_aceptacion_fisico',
            field=models.FileField(blank=True, upload_to='formatos_aceptacion/fisico/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Use PDF del formato físico (para validar el número).')], verbose_name='Formato de aceptación en físico'),
        ),
        migrations.AlterField(
            model_name='formatoaceptacion',
            name='numero_formulario',
            field=models.PositiveIntegerField(db_index=True, help_text='Número del formato impreso. Debe coincidir con el del PDF físico que se suba.', unique=True, verbose_name='Nº formulario'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='validacion_abono',
            field=models.CharField(choices=[('NO_APLICA', 'No requiere validación'), ('PENDIENTE', 'Pendiente de gerencia'), ('VALIDADO', 'Abono confirmado en cuenta'), ('RECHAZADO', 'Rechazado por gerencia')], db_index=True, default='NO_APLICA', help_text='Reserva, prima, cuotas a plazos y abono a capital: gerencia confirma el depósito en cuenta antes de emitir recibo al cliente.', max_length=12, verbose_name='Validación de abono'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='porcentaje_comision_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), help_text='Porcentaje de comisión sobre el precio de venta. Se copia al contrato al elegir este vendedor; con eso se calcula el recibo de comisión de venta.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
