# Generated by Django 6.0.3 on 2026-07-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0041_formato_numero_manual_pdf_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='plan_anos',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 año'), (2, '2 años'), (3, '3 años'), (4, '4 años'), (5, '5 años'), (10, '10 años'), (15, '15 años')], help_text='Plazo de financiamiento propio (años).', null=True),
        ),
        migrations.AlterField(
            model_name='formatoaceptacion',
            name='letra_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='La escribe el vendedor. Meses 1–12 sin interés; desde el mes 13 ya va con intereses.', max_digits=14, null=True, verbose_name='Cuota meses 1–12 (sin interés)'),
        ),
    ]
