# Generated by Django 6.0.3 on 2026-07-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0042_contrato_plan_anos_1_a_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoaceptacion',
            name='prima_1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de la reserva (se paga al llenar el formato).', max_digits=14, null=True, verbose_name='Reserva $'),
        ),
        migrations.AlterField(
            model_name='formatoaceptacion',
            name='prima_1_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago de reserva'),
        ),
        migrations.AlterField(
            model_name='formatoaceptacion',
            name='prima_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de la prima / enganche (se paga después de la reserva).', max_digits=14, null=True, verbose_name='Prima a pagar $'),
        ),
        migrations.AlterField(
            model_name='formatoaceptacion',
            name='prima_2_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago de prima'),
        ),
    ]
