# Generated by Django 6.0.3 on 2026-07-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0043_formato_reserva_prima_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='voucher_transferencia',
            field=models.FileField(blank=True, help_text='Comprobante PDF (o imagen) de la transferencia/depósito bancario.', null=True, upload_to='pagos/vouchers/%Y/%m/', verbose_name='Voucher de transferencia (PDF)'),
        ),
    ]
