# Generated by Django 6.0.3 on 2026-07-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0044_pago_voucher_transferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='concepto',
            field=models.CharField(choices=[('RESERVA', 'Reserva pagada'), ('PRIMA', 'Prima pagada (recibo)'), ('CUOTA', 'Cuota de financiamiento (plazos)'), ('MANTENIMIENTO', 'Cuota de mantenimiento'), ('ABONO_CAPITAL', 'Abono a capital'), ('MORA', 'Recargo administrativo'), ('OTRO', 'Otro')], max_length=24),
        ),
    ]
