# Generated by Django 6.0.3 on 2026-07-27 05:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0045_pago_concepto_prima_pagada_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_recargo_incluido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Parte del monto total que corresponde a recargo administrativo (días de gracia vencidos). No reduce el capital del contrato.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Recargo administrativo incluido'),
        ),
    ]
