# Generated by Django 6.0.3 on 2026-07-29 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0047_pago_concepto_contado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoaceptacion',
            name='contrato_compraventa_escaneado',
            field=models.FileField(blank=True, help_text='Escritura o contrato de compraventa firmado; forma parte del expediente del formato.', upload_to='formatos_aceptacion/compraventa/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'], message='Use PDF, JPG o PNG.')], verbose_name='Contrato de compraventa (PDF)'),
        ),
    ]
