# Generated by Django 6.0.3 on 2026-08-03 01:12

import django.core.validators
import inmobiliaria.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0048_formato_compraventa_escaneado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='dui_frente',
            field=models.FileField(blank=True, upload_to='vendedores/dui/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'], message='Use PDF o imagen (JPG, PNG, WEBP).')], verbose_name='Copia de DUI (enfrente)'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='dui_reverso',
            field=models.FileField(blank=True, upload_to='vendedores/dui/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg', 'webp'], message='Use PDF o imagen (JPG, PNG, WEBP).')], verbose_name='Copia de DUI (reverso)'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='giro',
            field=models.CharField(blank=True, help_text='Actividad económica (solo si es contribuyente).', max_length=200, verbose_name='Giro'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='nit',
            field=models.CharField(blank=True, max_length=20, validators=[inmobiliaria.validators.validar_nit_sv], verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='nrc',
            field=models.CharField(blank=True, max_length=30, verbose_name='NRC'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='tipo_persona',
            field=models.CharField(choices=[('NATURAL', 'Natural'), ('CONTRIBUYENTE', 'Contribuyente')], default='NATURAL', help_text='Persona natural o contribuyente (con NIT, NRC y giro).', max_length=20),
        ),
    ]
