# Generated by Django 6.0.3 on 2026-08-03 18:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0049_vendedor_tipo_contribuyente_dui_docs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroEtapaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasta_preventa', models.PositiveIntegerField(default=20, help_text='Con menos de este número de lotes comprometidos en el proyecto → Preventa.', verbose_name='Hasta preventa (lotes comprometidos)')),
                ('hasta_promocional', models.PositiveIntegerField(default=40, help_text='Desde preventa hasta este número → Promocional. Después → Pos preventa.', verbose_name='Hasta promocional')),
                ('hasta_pos_preventa', models.PositiveIntegerField(default=63, help_text='Solo informativo (rango mostrado en pantallas).', verbose_name='Tope pos preventa (referencia)')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro de etapas de venta',
                'verbose_name_plural': 'Parámetros de etapas de venta',
            },
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='etapa_venta_aplicada',
            field=models.CharField(blank=True, help_text='PREVENTA / PROMOCIONAL / POS_PREVENTA al momento de fijar el precio del sistema.', max_length=20, verbose_name='Etapa de venta aplicada'),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='precio_solicitado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='precio_solicitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_precio_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='precio_solicitud_motivo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo del cambio de precio'),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='precio_validacion_nota',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='precio_validado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='precio_validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_precio_validados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='validacion_precio',
            field=models.CharField(choices=[('NO_APLICA', 'Sin cambio'), ('PENDIENTE', 'Pendiente de gerencia'), ('APROBADO', 'Cambio aprobado'), ('RECHAZADO', 'Cambio rechazado')], db_index=True, default='NO_APLICA', max_length=20, verbose_name='Validación de precio'),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='valor_inmueble_sistema',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio automático del lote según la etapa del proyecto al elegir el lote.', max_digits=14, null=True, verbose_name='Valor según etapa (sistema)'),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='valor_inmueble_solicitado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nuevo valor pedido por ventas; aplica solo si gerencia aprueba.', max_digits=14, null=True, verbose_name='Valor solicitado (cambio)'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio_pos_preventa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de contado en etapa Pos preventa.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio contado — Pos preventa'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio_preventa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de contado en etapa Preventa.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio contado — Preventa'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='precio_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de contado en etapa Promocional.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio contado — Promocional'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_lista',
            field=models.DecimalField(decimal_places=2, help_text='Precio vigente (se sincroniza con la etapa actual del proyecto).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
