# Generated by Django 6.0.3 on 2026-08-03 23:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0051_backfill_precios_etapa_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='monto_prima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto total de prima/enganche de este proyecto. En el formato: Reserva + Prima a pagar = este valor. La prima a pagar se calcula sola (prima total − reserva).', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prima total del proyecto ($)'),
        ),
    ]
