# Generated by Django 6.0.3 on 2026-08-03 23:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0052_proyecto_monto_prima'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='porcentaje_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje del valor del lote que se cobra como reserva al llenar el formato. Ej.: 5 = 5 %. La reserva se calcula sola: valor del lote × este %.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Reserva (% del valor del lote)'),
        ),
    ]
