# Generated by Django 6.0.3 on 2026-08-03 23:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0053_proyecto_porcentaje_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='monto_prima',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='porcentaje_prima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje del valor del lote que corresponde a la prima/enganche total. En el formato: Reserva + Prima a pagar = valor × este %. La prima a pagar se calcula sola (prima total − reserva).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Prima total (% del valor del lote)'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='porcentaje_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje del valor del lote que se cobra como reserva al llenar el formato. Ej.: 5 = 5 %. Debe ser menor o igual a la prima total %.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Reserva (% del valor del lote)'),
        ),
    ]
