# Generated by Django 6.0.3 on 2026-08-04 02:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0054_proyecto_prima_porcentaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmueble',
            options={'ordering': ['proyecto', 'poligono__orden', 'poligono__nombre', 'codigo'], 'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'ordering': ['apellidos', 'nombres'], 'verbose_name': 'Asesor de ventas', 'verbose_name_plural': 'Asesores de ventas'},
        ),
        migrations.AlterUniqueTogether(
            name='inmueble',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Usuario interno (se sincroniza si el asesor de ventas tiene vínculo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_como_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vendedor_perfil',
            field=models.ForeignKey(blank=True, help_text='Asesor de ventas del módulo de ventas; define comisión sugerida y recibo de comisión.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='inmobiliaria.vendedor', verbose_name='Asesor de ventas (catálogo)'),
        ),
        migrations.AlterField(
            model_name='formatoaceptacion',
            name='firma_vendedor',
            field=models.ImageField(blank=True, upload_to='formatos_aceptacion/firmas/%Y/%m/', verbose_name='Firma asesor de ventas'),
        ),
        migrations.AlterField(
            model_name='formatoaceptacion',
            name='letra_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='La escribe el asesor de ventas. Meses 1–12 sin interés; desde el mes 13 ya va con intereses.', max_digits=14, null=True, verbose_name='Cuota meses 1–12 (sin interés)'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='codigo',
            field=models.CharField(db_index=True, help_text='Número o referencia del lote dentro del polígono (ej. 1, A-15). Puede repetirse en otro polígono del mismo proyecto.', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='porcentaje_comision_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('3'), help_text='Porcentaje de comisión sobre el precio de venta. Se copia al contrato al elegir este asesor de ventas; con eso se calcula el recibo de comisión de venta.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='usuario_vinculo',
            field=models.ForeignKey(blank=True, help_text='Usuario interno opcional si el asesor de ventas tiene cuenta en el sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor_catalogo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='inmueble',
            constraint=models.UniqueConstraint(condition=models.Q(('poligono__isnull', False)), fields=('proyecto', 'poligono', 'codigo'), name='inmueble_unico_proyecto_poligono_codigo'),
        ),
        migrations.AddConstraint(
            model_name='inmueble',
            constraint=models.UniqueConstraint(condition=models.Q(('poligono__isnull', True)), fields=('proyecto', 'codigo'), name='inmueble_unico_proyecto_codigo_sin_poligono'),
        ),
    ]
