# Generated by Django 6.0.3 on 2026-08-04 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0055_inmueble_unico_por_poligono_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='validacion_gerencia',
            field=models.CharField(choices=[('NO_APLICA', 'No requiere (admin/gerencia)'), ('PENDIENTE', 'Pendiente de gerencia'), ('VALIDADO', 'Validado por gerencia'), ('RECHAZADO', 'Rechazado por gerencia')], db_index=True, default='NO_APLICA', help_text='Si lo registra un operador, queda pendiente hasta que admin/gerencia lo valide.', max_length=12, verbose_name='Validación de gerencia'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='validacion_gerencia_nota',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contrato',
            name='validado_gerencia_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='validado_gerencia_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_validados_gerencia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='validacion_gerencia',
            field=models.CharField(choices=[('NO_APLICA', 'No requiere (admin/gerencia)'), ('PENDIENTE', 'Pendiente de gerencia'), ('VALIDADO', 'Validado por gerencia'), ('RECHAZADO', 'Rechazado por gerencia')], db_index=True, default='NO_APLICA', help_text='Si lo registra un operador, queda pendiente hasta que admin/gerencia lo valide.', max_length=12, verbose_name='Validación de gerencia'),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='validacion_gerencia_nota',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='validado_gerencia_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formatoaceptacion',
            name='validado_gerencia_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_validados_gerencia', to=settings.AUTH_USER_MODEL),
        ),
    ]
