# Generated by Django 6.0.3 on 2026-08-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0056_validacion_gerencia_formato_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='plan_anos',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 año'), (2, '2 años'), (3, '3 años'), (4, '4 años'), (5, '5 años'), (6, '6 años'), (10, '10 años'), (15, '15 años')], help_text='Plazo de financiamiento propio (años).', null=True),
        ),
    ]
